class Analista {
  final String idAnalista;
  final String name;
  final String lastName;
  final String dni;
  final String sexo;
  final String edad;
  final String fechaNacimiento;
  final String cellphone;
  final String email;
  final String address;
  final String district;
  final String province;
  final String region;

  final String idSupervisor;
  Analista(
      this.idAnalista,
      this.name,
      this.lastName,
      this.dni,
      this.sexo,
      this.edad,
      this.fechaNacimiento,
      this.cellphone,
      this.email,
      this.address,
      this.district,
      this.province,
      this.region,
      this.idSupervisor);
}

List<Analista> getAnalistas() {
  final List<Analista> analistas = [
    Analista(
        "1",
        "Arled",
        "Vallenas Suarez",
        "96543025",
        "Femenino",
        "39",
        "03/02/1985",
        "978563412",
        'abcd@gmail.com',
        "Av. La cultura 322",
        "Cusco",
        "Cusco",
        "Cusco",
        "1"),
    Analista(
        "2",
        "Ana",
        "Cortez Quispe",
        "98765432",
        "Femenino",
        "36",
        "03/02/1988",
        "978563412",
        "foo@gmail.com",
        "Av. La cultura 666",
        "Cusco",
        "Cusco",
        "Cusco",
        "2"),
    Analista(
        "3",
        "Glina ",
        "Puma Huamaní",
        "70236598",
        "Femenino",
        "34",
        "03/02/1990",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 6",
        "Cusco",
        "Cusco",
        "Cusco",
        "3"),
    Analista(
        "4",
        "Roswell",
        "Pando Muñoz",
        "36402598",
        "Masculino",
        "32",
        "03/02/1992",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 75",
        "Cusco",
        "Cusco",
        "Cusco",
        "2"),
    Analista(
        "5",
        "Yoshimori",
        "Lavilla Quispe",
        "32597322",
        "Masculino",
        "27",
        "03/02/1997",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 145",
        "Cusco",
        "Cusco",
        "Cusco",
        "4"),
    Analista(
        "6",
        "Mishel",
        "Turpo Meza",
        "23014586",
        "Masculino",
        "30",
        "03/02/1994",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 315",
        "Cusco",
        "Cusco",
        "Cusco",
        "1"),
    Analista(
        "7",
        "Anyi",
        "Mujica Hermoza",
        "35987645",
        "Femenino",
        "26",
        "03/02/1998",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 299",
        "Cusco",
        "Cusco",
        "Cusco",
        "6"),
    Analista(
        "8",
        "Milagros",
        "Moreano Sarayasi",
        "15798642",
        "Femenino",
        "29",
        "03/02/1995",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 245",
        "Cusco",
        "Cusco",
        "Cusco",
        "3"),
    Analista(
        "9",
        "Julia",
        "Ramos Gutierrez",
        "36501263",
        "Femenino",
        "32",
        "03/02/1992",
        "978563412",
        "foo@gmail.com",
        "Av. La cultura 1045",
        "Cusco",
        "Cusco",
        "Cusco",
        "2"),
    Analista(
        "10",
        "Mario",
        "Mendoza Juarez",
        "54698230",
        "Masculino",
        "32",
        "03/02/1992",
        "978563412",
        "foo@gmail.com",
        "Av. La cultura 399",
        "Cusco",
        "Cusco",
        "Cusco",
        "4"),
  ];
  return analistas;
}
