class Supervisor {
  final String number;
  final String name;
  final String lastName;
  final String dni;
  final String sexo;
  final String edad;
  final String fechaNacimiento;
  final String cellphone;
  final String email;
  final String address;
  final String district;
  final String province;
  final String region;
  final String riesgoSocio;
  final String tipoSocio;
  final String tipoCredito;
  final String tipoProducto;
  final String modalidad;
  final String nombrePrestamo;
  final String creditoTotal;
  final String plazo;
  final String tasaInteres;
  final String fechaAprobacion;
  final String ultimaFechaPago;
  final String montoCuota;
  final String saldoVencido;
  final String saldoCredito;
  DateTime? assignedDate;
  final String tipoGrupo;
  Supervisor(
      this.number,
      this.name,
      this.lastName,
      this.dni,
      this.sexo,
      this.edad,
      this.fechaNacimiento,
      this.cellphone,
      this.email,
      this.address,
      this.district,
      this.province,
      this.region,
      this.riesgoSocio,
      this.tipoSocio,
      this.tipoCredito,
      this.tipoProducto,
      this.modalidad,
      this.nombrePrestamo,
      this.creditoTotal,
      this.plazo,
      this.tasaInteres,
      this.fechaAprobacion,
      this.ultimaFechaPago,
      this.montoCuota,
      this.saldoVencido,
      this.saldoCredito,
      this.tipoGrupo,
      {this.assignedDate});
}

List<Supervisor> getSupervisores() {
  final List<Supervisor> supervisores = [
    Supervisor(
        "1",
        "Arled",
        "Vallenas Suarez",
        "96543025",
        "Femenino",
        "39",
        "03/02/1985",
        "978563412",
        'abcd@gmail.com',
        "Av. La cultura 322",
        "Cusco",
        "Cusco",
        "Cusco",
        "NORMAL",
        "CAMPAÑA",
        "CONSUMO",
        "INSTITUCIONAL",
        "COOPENAVIDEÑO",
        "CONSUMO NO REVOLVENTE",
        "40 000",
        "60",
        "15.25",
        "24/12/2018",
        "16/012024",
        "972.27",
        "0",
        "40 000",
        assignedDate: DateTime.now(),
        "Seguimiento"),
    Supervisor(
        "2",
        "Ana",
        "Cortez Quispe",
        "98765432",
        "Femenino",
        "36",
        "03/02/1988",
        "978563412",
        "foo@gmail.com",
        "Av. La cultura 666",
        "Cusco",
        "Cusco",
        "Cusco",
        "NORMAL",
        "RECURRENTE",
        "COMERCIAL",
        "MININEGOCIO",
        "GENÉRICO",
        "CRÉDITOS A PEQUEÑAS EMPRESAS",
        "27 000",
        "36",
        "32.15",
        "9/06/2018",
        "10/06/2021",
        "1148.27",
        "6 025,59",
        "23 974,41",
        assignedDate: DateTime.now(),
        "Promoción"),
    Supervisor(
        "3",
        "Glina ",
        "Puma Huamaní",
        "70236598",
        "Femenino",
        "34",
        "03/02/1990",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 6",
        "Cusco",
        "Cusco",
        "Cusco",
        "NORMAL",
        "CAMPAÑA",
        "CONSUMO",
        "INSTITUCIONAL",
        "COOPENAVIDEÑO",
        "CONSUMO NO REVOLVENTE",
        "40 000",
        "60",
        "15.25",
        "24/12/2018",
        "16/012024",
        "972.27",
        "0",
        "40 000",
        assignedDate: DateTime(2024, 1, 7),
        "Recuperación"),
    Supervisor(
        "4",
        "Roswell",
        "Pando Muñoz",
        "36402598",
        "Masculino",
        "32",
        "03/02/1992",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 75",
        "Cusco",
        "Cusco",
        "Cusco",
        "NORMAL",
        "RECURRENTE",
        "COMERCIAL",
        "MININEGOCIO",
        "GENÉRICO",
        "CRÉDITOS A PEQUEÑAS EMPRESAS",
        "27 000",
        "36",
        "32.15",
        "9/06/2018",
        "10/06/2021",
        "1148.27",
        "6 025,59",
        "23 974,41",
        assignedDate: DateTime(2024, 1, 6),
        "Seguimiento"),
    Supervisor(
        "5",
        "Yoshimori",
        "Lavilla Quispe",
        "32597322",
        "Masculino",
        "27",
        "03/02/1997",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 145",
        "Cusco",
        "Cusco",
        "Cusco",
        "NORMAL",
        "RECURRENTE",
        "COMERCIAL",
        "MININEGOCIO",
        "GENÉRICO",
        "CRÉDITOS A PEQUEÑAS EMPRESAS",
        "27 000",
        "36",
        "32.15",
        "9/06/2018",
        "10/06/2021",
        "1148.27",
        "6 025,59",
        "23 974,41",
        assignedDate: DateTime.now(),
        "Promoción"),
    Supervisor(
        "6",
        "Mishel",
        "Turpo Meza",
        "23014586",
        "Masculino",
        "30",
        "03/02/1994",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 315",
        "Cusco",
        "Cusco",
        "Cusco",
        "NORMAL",
        "CAMPAÑA",
        "CONSUMO",
        "INSTITUCIONAL",
        "COOPENAVIDEÑO",
        "CONSUMO NO REVOLVENTE",
        "40 000",
        "60",
        "15.25",
        "24/12/2018",
        "16/012024",
        "972.27",
        "0",
        "40 000",
        assignedDate: DateTime(2024, 1, 7),
        "Recuperación"),
    Supervisor(
        "7",
        "Anyi",
        "Mujica Hermoza",
        "35987645",
        "Femenino",
        "26",
        "03/02/1998",
        "978563412",
        'abcd@gmail.com',
        "Jr. Jose Carlos Mariategui 299",
        "Cusco",
        "Cusco",
        "Cusco",
        "NORMAL",
        "RECURRENTE",
        "COMERCIAL",
        "MININEGOCIO",
        "GENÉRICO",
        "CRÉDITOS A PEQUEÑAS EMPRESAS",
        "27 000",
        "36",
        "32.15",
        "9/06/2018",
        "10/06/2021",
        "1148.27",
        "6 025,59",
        "23 974,41",
        assignedDate: DateTime.now(),
        "Seguimiento"),
  ];
  return supervisores;
}
